[package]
name = "nimrod"
version = "0.1.0"
edition = "2024"
authors = ["Johann Kempter <admin@binflip.rs>"]
rust-version = "1.85"
description = "Parse and inspect Nim-compiled native binaries"
license = "Apache-2.0"
repository = "https://github.com/BinFlip/nimrod"
readme = "README.md"
keywords = ["nim", "reverse-engineering", "parser", "binary-analysis", "malware"]
categories = ["parser-implementations"]

[dependencies]
goblin = "0.10.5"
memchr = "2.8.0"

[dev-dependencies]
proptest = "1.11.0"
